import assert from "node:assert/strict";
import { execFile, spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const execFileAsync = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const cliPath = join(__dirname, "..", "dist", "index.js");

function runCli(
  args: readonly string[],
  cwd: string,
): Promise<{ code: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [cliPath, ...args], {
      cwd,
      env: { ...process.env, DEV_AGENT_MODEL_PROVIDER: "ollama" },
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => { stdout += chunk; });
    child.stderr.on("data", (chunk) => { stderr += chunk; });
    child.on("close", (code) => resolve({ code, stdout, stderr }));
  });
}

async function withProject(run: (project: string) => Promise<void>): Promise<void> {
  const project = await mkdtemp(join(tmpdir(), "dev-agent-workflow-cli-"));
  try {
    await run(project);
  } finally {
    await rm(project, { recursive: true, force: true });
  }
}

test("review is provider-free and returns machine-readable change metadata", async () => {
  await withProject(async (project) => {
    await execFileAsync("git", ["init", "--quiet"], { cwd: project });
    await writeFile(join(project, "changed.txt"), "initial\n", "utf8");
    await execFileAsync("git", ["add", "changed.txt"], { cwd: project });
    await execFileAsync("git", ["-c", "user.email=dev-agent@example.invalid", "-c", "user.name=dev-agent", "commit", "-m", "initial", "--quiet"], { cwd: project });
    await writeFile(join(project, "changed.txt"), "changed\n", "utf8");

    const result = await runCli(["review", "--cwd", project, "--json", "--non-interactive"], project);
    assert.equal(result.code, 0, result.stderr);
    assert.equal(result.stderr, "");
    const payload = JSON.parse(result.stdout);
    assert.equal(payload.command, "review");
    assert.equal(payload.status, "ok");
    assert.deepEqual(payload.changedFiles, [{ path: "changed.txt", status: "modified", additions: 1, deletions: 1 }]);
  });
});

test("plan and apply rehydrate a metadata-only plan across separate CLI processes", async () => {
  await withProject(async (project) => {
    const changesPath = join(project, "changes.json");
    const planPath = join(project, "plan.json");
    await writeFile(changesPath, JSON.stringify([
      { action: "write", path: "generated.txt", content: "generated by plan\n" },
    ]), "utf8");

    const planned = await runCli([
      "plan", "--cwd", project, "--changes-file", "changes.json", "--plan-file", "plan.json", "--session", "ci", "--json", "--non-interactive",
    ], project);
    assert.equal(planned.code, 0, planned.stderr);
    const planPayload = JSON.parse(planned.stdout);
    assert.equal(planPayload.command, "plan");
    assert.equal(planPayload.plan.mutations[0].path, "generated.txt");
    assert.doesNotMatch(await readFile(planPath, "utf8"), /generated by plan/);
    assert.doesNotMatch(await readFile(planPath, "utf8"), new RegExp(project.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));

    const applied = await runCli([
      "apply", "--cwd", project, "--changes-file", "changes.json", "--plan-file", "plan.json", "--session", "ci", "--json", "--non-interactive",
    ], project);
    assert.equal(applied.code, 0, applied.stderr);
    const applyPayload = JSON.parse(applied.stdout);
    assert.equal(applyPayload.command, "apply");
    assert.equal(await readFile(join(project, "generated.txt"), "utf8"), "generated by plan\n");
  });
});

test("non-interactive mode fails closed instead of waiting for stdin", async () => {
  await withProject(async (project) => {
    const result = await runCli(["--non-interactive", "--json"], project);
    assert.equal(result.code, 3);
    const payload = JSON.parse(result.stdout);
    assert.equal(payload.error.code, "needs_input");
  });
});
